### ISSUE TITLE
Glyph vs. Glyph spec

### ISSUE THREAD

**Issue by jakebeal** [BDAthlon/2017-Triple_Helix-1#3]
The recently adopted [SEP V001 ](https://github.com/SynBioDex/SBOLv-realizations/issues/4) now provides for glyphs having not just the plain black and white version, but a spec with bounding box, interior, and recommended backbone alignment.

The glyph repository should allow you to see both of these.

**Comment by jamesscottbrown** [comment]
Thank you for pointing this out. I will add the ability to upload "glyph specification" images.

Are there any such images that are officially approved yet? The SEP has 3 examples, but describes 2 of these as "possible".

**Comment by jakebeal** [comment]
The [develop branch](https://github.com/SynBioDex/SBOLv-realizations/tree/develop) has been updated to contain specifications of all of the SBOL Visual 1.0 glyphs --- it's just that some are not yet fully specified, however, because they were ambiguous.

**Comment by jamesscottbrown** [comment]
This is now supported, and I've uploaded the specification images from that branch ([example](http://glyphs.jamesscottbrown.com/glyph/29)).
